version: 2

sources:
  - name: raw_data 
    database: finance_db
    schema: raw #where raw_data is stored
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products